baseURL = "https://caffeine-fighter.github.io/"
languageCode = "ko-kr"
defaultContentLanguage = "ko"
title = "카페인파이터의 일기장"

[sitemap]
# always, hourly daily, weekly, monthly, yearly, never
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

  
[module]
  [[module.imports]]
    path = "github.com/CaiJimmy/hugo-theme-stack/v4"

[params]
  math = true

  [params.search]
    enabled = true


[[menu.main]]
  identifier = "categories"
  name = "Categories"
  url = "/categories/"
  weight = 3

